# Generated by Django 4.2 on 2023-07-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_alter_postimage_image_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image_source',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
